### ISSUE TITLE
Can't associate mock with symfony service

### ISSUE THREAD

**Issue by bogdan-dubyk** [Codeception/module-symfony#89]
I have a lot of API calls and I want to mock API client in functional tests. Note: I run this process by Symfony command

But I'm still getting real API response

I have such a test case (simplified)

```php
     $request = new Request(
                SymfonyRequest::METHOD_GET,
                'https://someurl.com/Apiv3/apps'
            );

        $apiClientMock = \Mockery::mock(HttpClientInterface::class);
        $apiClientMock
            ->shouldReceive('send')
            ->once()
            ->with(request)
            ->andReturn(new Response(HttpCode::OK, [], '{"data":"some data"}'));
        $I->replaceSymfonyServiceWithMock($apiClientMock);

        $I->runShellCommand('bin/console sync:apps');
```

and logic of `replaceSymfonyServiceWithMock`inside of functional helper
```php
    /**
     * @param MockInterface $object
     * @param string|null $alias
     * @throws \Codeception\Exception\ModuleException
     */
    public function replaceSymfonyServiceWithMock(MockInterface $object, string $alias = null)
    {
        /** @var Symfony $symfony */
        $symfony = $this->getModule('Symfony');
        $testContainer = $symfony->grabService('test.service_container');

        if($alias !== null) {
            $alias = get_class($object);
        }

        $testContainer->set($alias, $object);
        $symfony->persistService($alias, false);
    }

```

### Details

* Codeception version: 2.4
* PHP Version: 7.2.10
* Operating System: MacOs
* Installation type: Composer
* Suite configuration:

```yml

actor: FunctionalTester
modules:
    enabled:
        - Symfony:
            app_path: src
            kernel_class: App\Kernel
            environment: test
        - Doctrine2:
            depends: Symfony
            cleanup: true
        - REST:
            depends: Symfony
            part: json
        - Cli
        - Mockery
        - \Helper\Functional
```
