### ISSUE TITLE
"The EntityManager is closed" with Symfony and Doctrine2 modules

### ISSUE THREAD

**Issue by benr77** [Codeception/module-symfony#92]
#### What are you trying to achieve?

Use the Symfony and Doctrine2 modules together, to allow "cleanup" by reversing transactions between tests, in functional tests against an SQLite database.

#### What do you get instead?

Many tests are simply failing with

```bash
[Doctrine\ORM\ORMException] The EntityManager is closed.
```
If I do not enable the Doctrine2 module, the tests all succeed. But without it enabled, the transactions are not implemented and reversed between tests.

functional.suite.yml is as follows

```yml
class_name: FunctionalTester
modules:
  enabled:
    - \Helper\Functional
    - Asserts
    - Cli
    - Filesystem
    - REST
    - Symfony:
        environment: test
        var_path: 'var'
    - Doctrine2:
        depends: Symfony
        cleanup: true
```
### Details

* Codeception version: 2.4.5
* PHP Version: 7.2
* Operating System: Linux Mint
* Installation type: Composer
